### ISSUE TITLE
ga4-flattener-cfconfigbuilder fails

### ISSUE THREAD

**Issue by czerwonka** [adswerve/google_analytics_flattener_ga4#20]
Hello,

have some problems with setting up the flattener.
Function ga4-flattener-cfconfigbuilder fails, with error same as in issue "config_datasets.json is not created #18", so I add config file manually. I think is is also data processing location problem, because my dataset is in EU multi region.

Main issue is with the function ga4-flattener-cfconfigbuilder, test fails with this error: I think is also data processing location problem, because my dataset is in EU.  Config file looks ok.

`resource: {2}
severity: "ERROR"
textPayload: "Exception on / [POST]
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/functions_framework/__init__.py", line 171, in view_func
    function(data, context)
  File "/workspace/main.py", line 385, in flatten_ga_data
    input_event = InputValidator(event)
  File "/workspace/main.py", line 17, in __init__
    message_payload = json.loads(base64.b64decode(event['data']).decode('utf-8'))
KeyError: 'data'"
timestamp: "2023-03-16T13:09:14.335783Z"
trace: "projects/oferteo-tst-ga4/traces/bf99c5838edbf405e567bab2ea04d0f0"`

**Comment by RuslanBergenov** [comment]
Did you end up building the config file? Flattener working okay now? Any further questions?
