### ISSUE TITLE
Errors in config builder function

### ISSUE THREAD

**Issue by RuslanBergenov** [adswerve/google_analytics_flattener_ga4#24]

**Comment by RuslanBergenov** [comment]
It does build a config, but then crashes with this error

```
DEFAULT 2023-11-01T16:44:11.532249Z [resource.labels.functionName: ga4-flattener-deployment-cfconfigbuilder] [labels.executionId: xrzrcoxafdur] TypeError: The view function for 'run' did not return a valid response. The function either returned None or ended without a return statement.
DEBUG 2023-11-01T16:44:10.518635775Z [resource.labels.functionName: ga4-flattener-deployment-cfconfigbuilder] [labels.executionId: xrzrcoxafdur] Function execution took 7232 ms, finished with status: 'crash'
DEFAULT 2023-11-01T16:44:10.516457Z [resource.labels.functionName: ga4-flattener-deployment-cfconfigbuilder] [labels.executionId: xrzrcoxafdur] raise TypeError(
DEFAULT 2023-11-01T16:44:10.516451Z [resource.labels.functionName: ga4-flattener-deployment-cfconfigbuilder] [labels.executionId: xrzrcoxafdur] File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 2138, in make_response
DEFAULT 2023-11-01T16:44:10.516443Z [resource.labels.functionName: ga4-flattener-deployment-cfconfigbuilder] [labels.executionId: xrzrcoxafdur] ^^^^^^^^^^^^^^^^^^^^^^
DEFAULT 2023-11-01T16:44:10.516437Z [resource.labels.functionName: ga4-flattener-deployment-cfconfigbuilder] [labels.executionId: xrzrcoxafdur] response = self.make_response(rv)
DEFAULT 2023-11-01T16:44:10.516431Z [resource.labels.functionName: ga4-flattener-deployment-cfconfigbuilder] [labels.executionId: xrzrcoxafdur] File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 1845, in finalize_request
DEFAULT 2023-11-01T16:44:10.516423Z [resource.labels.functionName: ga4-flattener-deployment-cfconfigbuilder] [labels.executionId: xrzrcoxafdur] ^^^^^^^^^^^^^^^^^^^^^^^^^
DEFAULT 2023-11-01T16:44:10.516416Z [resource.labels.functionName: ga4-flattener-deployment-cfconfigbuilder] [labels.executionId: xrzrcoxafdur] return self.finalize_request(rv)
DEFAULT 2023-11-01T16:44:10.516401Z [resource.labels.functionName: ga4-flattener-deployment-cfconfigbuilder] [labels.executionId: xrzrcoxafdur] File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 1826, in full_dispatch_request
DEFAULT 2023-11-01T16:44:10.516392Z [resource.labels.functionName: ga4-flattener-deployment-cfconfigbuilder] [labels.executionId: xrzrcoxafdur] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 2023-11-01T16:44:10.516386Z [resource.labels.functionName: ga4-flattener-deployment-cfconfigbuilder] [labels.executionId: xrzrcoxafdur] Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app response = self.full_dispatch_request()
DEFAULT 2023-11-01T16:44:10.516337Z [resource.labels.functionName: ga4-flattener-deployment-cfconfigbuilder] [labels.executionId: xrzrcoxafdur] ERROR:build_ga_flattener_config:Exception on / [POST]
DEBUG 2023-11-01T16:44:03.285711146Z [resource.labels.functionName: ga4-flattener-deployment-cfconfigbuilder] [labels.executionId: xrzrcoxafdur] Function execution started
```

**Comment by RuslanBergenov** [comment]
Fixed
